# -*- coding: utf-8 -*-
"""Algoritmo_Hash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6TEDy6prSXSGJepfWVPbLN26cmr6CFw
"""

import random
import string

# 1. TEXTO -> BINARIO
def texto_a_binario(texto: str) -> str:
    """Convierte cada letra del texto en una cadena binaria de 8 bits."""
    if not texto:
        # Previene errores si el texto está vacío
        return "00000000"

    return "".join(format(ord(c), '08b') for c in texto)

# 2. CONTAR PATRONES (CON TAMAÑO DINÁMICO)
def contar_patrones(binario: str, bits_por_patron: int) -> list:
    """Cuenta cuántas veces aparecen los pares 00, 01, 10 y 11 y aplica el límite matemático."""
    p = [0, 0, 0, 0]

    for i in range(0, len(binario) - 1, 2):
        par = binario[i:i+2]
        if par == "00": p[0] += 1
        elif par == "01": p[1] += 1
        elif par == "10": p[2] += 1
        elif par == "11": p[3] += 1

    # Límite matemático para evitar que el número exceda los bits asignados
    limite = 2 ** bits_por_patron
    p_fijo = [val % limite for val in p]

    return p_fijo

# 3. ESTADÍSTICAS -> BINARIO
def estadisticas_a_binario(p: list, bits_por_patron: int) -> str:
    """Convierte los contadores de vuelta a binario usando la cantidad exacta de bits."""
    # f'0{bits_por_patron}b' inyecta el tamaño
    formato = f'0{bits_por_patron}b'
    return "".join(format(val, formato) for val in p)

# 4. MEZCLA BINARIA (SEPARA 1s Y 0s)
def mezclar(binario: str) -> str:
    """Manda todos los unos a la izquierda y los ceros a la derecha."""
    unos = binario.count('1')
    ceros = binario.count('0')
    return ('1' * unos) + ('0' * ceros)

# 5. HASH FINAL
def generar_hash(texto: str, bits_totales: int) -> str:
    """Ejecuta todos los pasos y devuelve el hash con el tamaño de bits deseado."""
    # tenemos 4 patrones (00, 01, 10, 11), el total debe ser divisible entre 4
    if bits_totales % 4 != 0:
        raise ValueError("El tamaño de bits debe ser múltiplo de 4 (ej. 4, 8, 16, 32, 64)")

    bits_por_patron = bits_totales // 4

    binario = texto_a_binario(texto)
    patrones = contar_patrones(binario, bits_por_patron)
    stats_bin = estadisticas_a_binario(patrones, bits_por_patron)
    mezcla = mezclar(stats_bin)

    return mezcla

# 6. RECONSTRUCCIÓN (SIMULADA)
def reconstruir(hash_str: str, texto_original: str, bits_totales: int):
    """Genera textos aleatorios e intenta encontrar colisiones con el hash recibido."""
    print("\n==============================")
    print(" RECONSTRUCCIÓN DEL HASH ")
    print("==============================\n")
    print(f"Hash recibido ({len(hash_str)} bits):")
    print(hash_str + "\n")
    print("Intentando reconstruir posibles textos...\n")

    # Semilla para hacer el experimento replicable
    random.seed(len(texto_original) * 31)

    for i in range(10):
        # Genera un texto candidato aleatorio con la misma longitud que el original
        caracteres_posibles = string.ascii_letters
        candidato = "".join(random.choice(caracteres_posibles) for _ in range(len(texto_original)))
        # Generamos el hash del candidato usando el mismo tamaño de bits
        mezcla = generar_hash(candidato, bits_totales)

        print(f"Intento {i + 1}: {candidato}")
        print(f"Hash generado: {mezcla}")

        if mezcla == hash_str:
            print("✔ COMPATIBLE\n")
        else:
            print("✖ NO EXACTO\n")

    print("CONCLUSIÓN:")
    print("Existen múltiples posibles entradas compatibles.")
    print("No se puede determinar el texto original de forma única.")

# 7. MAIN
def main():
    texto = ""
    print(f"TEXTO ORIGINAL: {texto}\n")

    print("--- PRUEBAS DE TAMAÑO ---")

    hash_16 = generar_hash(texto, bits_totales=16)
    print(f"Hash de 16 bits: {hash_16}")

    # --- SIMULACIÓN DE RECONSTRUCCIÓN ---
    # simulación con el de 16 bits para el experimento
    bits_elegidos = 16
    hash_para_reconstruir = generar_hash(texto, bits_totales=bits_elegidos)
    reconstruir(hash_para_reconstruir, texto, bits_totales=bits_elegidos)

if __name__ == "__main__":
    main()