# -*- coding: utf-8 -*-
"""generación de números pseudoaleatorios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5R2F4cqlW_oRB6ho_U9irdzjYkTSa3V
"""

from collections import Counter
from typing import Tuple, List

def generador_congruencial_cuadratico(semilla_interna: int) -> Tuple[int, int]:
    """
    Genera un número pseudoaleatorio utilizando un modelo polinomial de segundo grado.

    Parámetros:
    -----------
    semilla_interna : int
        El estado interno actual de la secuencia (X_n).

    Retorna:
    --------
    Tuple[int, int]
        - x_siguiente (int): La nueva semilla para la siguiente iteración (X_{n+1}).
        - resultado_final (int): El número pseudoaleatorio proyectado al espacio de 20 valores (R_{n+1}).
    """
    # 1. Definición de las variables matemáticas del sistema
    a = 3   # Multiplicador cuadrático
    b = 5   # Multiplicador lineal
    c = 7   # Incremento constante
    M = 101 # Módulo principal (Número primo para mayor dispersión)
    k = 20  # Espacio muestral deseado (valores de 0 a 19)

    # 2. Evaluación del polinomio y aplicación del módulo M
    # Ecuación: X_{n+1} = (a*X_n^2 + b*X_n + c) mod M
    polinomio = (a * (semilla_interna ** 2)) + (b * semilla_interna) + c
    x_siguiente = polinomio % M

    # 3. Proyección al espacio de 20 valores
    # Ecuación: R_{n+1} = X_{n+1} mod k
    resultado_final = x_siguiente % k

    return x_siguiente, resultado_final

def simular_distribucion(semilla_inicial: int, iteraciones: int) -> None:
    """
    Ejecuta el generador múltiples veces y analiza la distribución matemática de los resultados.
    """
    semilla_actual = semilla_inicial
    resultados_generados: List[int] = []

    print("="*50)
    print(f" GENERACIÓN DE LOS PRIMEROS 5 NÚMEROS (Semilla: {semilla_inicial})")
    print("="*50)

    # Ejecutamos el ciclo matemático paso a paso
    for i in range(iteraciones):
        semilla_actual, numero_aleatorio = generador_congruencial_cuadratico(semilla_actual)
        resultados_generados.append(numero_aleatorio)

        # Mostramos solo los primeros 5 para ver el procedimiento
        if i < 5:
            print(f"Iteración {i+1}:")
            print(f"  -> Nueva semilla calculada : {semilla_actual}")
            print(f"  -> Número final (mod 20)   : {numero_aleatorio}\n")

    # ANÁLISIS ESTADÍSTICO
    # Contamos la frecuencia de cada número para demostrar que no da "resultados y ya"
    print("="*50)
    print(f" ANÁLISIS DE DISTRIBUCIÓN DESPUÉS DE {iteraciones} CICLOS")
    print("="*50)

    frecuencias = Counter(resultados_generados)

    # Imprimimos la distribución ordenada del 0 al 19
    for numero in range(20):
        conteo = frecuencias.get(numero, 0)
        # Representación visual de la frecuencia con barras (histograma en texto)
        barra = "█" * conteo
        print(f"Valor {numero:02d}: {barra} ({conteo} apariciones)")

# ==========================================
# Ejecución Principal
# ==========================================
if __name__ == "__main__":
    SEMILLA_USUARIO = 42
    CANTIDAD_A_GENERAR = 100 # Generamos 100 números para evaluar la dispersión

    simular_distribucion(SEMILLA_USUARIO, CANTIDAD_A_GENERAR)